---
- name: ARGOCD INSTALL | Deploy namespace
  import_tasks: namespace.yml

- name: ARGOCD INSTALL | Deploy Kubernetes objects
  import_tasks: kubernetes.yml

- name: ARGOCD INSTALL | Manage admin user
  import_tasks: user.yml

- name: ARGOCD INSTALL | Manage repositories
  import_tasks: repositories.yml

- name: ARGOCD INSTALL | Apply Argo CD application manifests
  kubernetes.core.k8s:
    src: "{{ item.root }}/{{ item.path }}"
  loop: "{{ query('filetree', '/Users/steelecooke/Documents/Projects/argocd/ansible/roles/argocd/manifests/') }}"
  when: item.state == 'file' and item.path.endswith('.yml')
