---
- name: ARGOCD INSTALL | Deploy namespace
  import_tasks: namespace.yml

- name: ARGOCD INSTALL | Deploy Kubernetes objects
  import_tasks: kubernetes.yml

- name: ARGOCD INSTALL | Manage admin user
  import_tasks: user.yml

- name: ARGOCD INSTALL | Manage repositories
  import_tasks: repositories.yml

- name: ARGOCD INSTALL | Apply Argo CD application manifests
  shell: kubectl apply -f {{ item }}
  loop: "{{ lookup('fileglob', 'roles/argocd/manifests/**/*.yml', wantlist=true) }}"
